'use client';

import { AlertCircle, ArrowRight, CalendarClock, Check, CircleAlert, Clock3, FileCheck2, Gauge, Radio, ShieldAlert, UsersRound, Eye, EyeOff } from 'lucide-react';
import type { OperationsMetric, TournamentOperationsData } from './types';

type Props = { data: TournamentOperationsData | null; loading: boolean; error: string; navigate: (href: string) => void };
const priorityClasses = { info: 'border-blue-200 bg-blue-50 text-blue-700', warning: 'border-amber-200 bg-amber-50 text-amber-800', critical: 'border-red-200 bg-red-50 text-red-700', success: 'border-emerald-200 bg-emerald-50 text-emerald-700' };
const emptyLabels: Record<string, string> = { Equipos: 'Sin equipos', Jugadores: 'Sin jugadores', Partidos: 'Sin partidos', 'Partidos hoy': 'Sin agenda', 'En vivo': 'Ninguno en vivo', 'Por jugar': 'Sin pendientes', 'Docs. pendientes': 'Sin pendientes', 'Sanciones activas': 'Sin sanciones' };

function Skeleton() {
  return <div className="space-y-6" aria-label="Cargando indicadores" aria-busy="true"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl border border-slate-200 bg-white p-4"><div className="h-8 w-14 rounded bg-slate-100" /><div className="mt-4 h-3 w-24 rounded bg-slate-100" /></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><div className="h-72 animate-pulse rounded-3xl bg-white" /><div className="h-72 animate-pulse rounded-3xl bg-white" /></div></div>;
}

function MetricValue({ metric, label }: { metric: OperationsMetric; label: string }) {
  if (metric.error) return <><p className="mt-4 text-3xl font-black leading-none text-slate-400">—</p><p role="status" className="mt-2 text-[9px] font-bold leading-tight text-red-600">No fue posible cargar este indicador</p></>;
  return <><p className="mt-4 text-3xl font-black leading-none tracking-tighter text-slate-950">{metric.value}</p><p className="mt-2 text-[9px] font-bold leading-tight text-slate-400">{metric.value === 0 ? emptyLabels[label] : 'Dato actualizado'}</p></>;
}

export default function OperationsDashboard({ data, loading, error, navigate }: Props) {
  if (loading) return <Skeleton />;
  if (error) return <div role="alert" className="flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-700"><AlertCircle className="mt-0.5 shrink-0" size={20} /><div><p className="text-sm font-black uppercase">No fue posible cargar el resumen</p><p className="mt-1 text-sm font-semibold">{error}</p></div></div>;
  if (!data) return null;
  const metrics = [
    { label: 'Equipos', metric: data.kpis.teams, icon: UsersRound, tone: 'text-blue-600 bg-blue-50' }, { label: 'Jugadores', metric: data.kpis.players, icon: UsersRound, tone: 'text-cyan-600 bg-cyan-50' }, { label: 'Partidos', metric: data.kpis.matches, icon: CalendarClock, tone: 'text-slate-700 bg-slate-100' }, { label: 'Partidos hoy', metric: data.kpis.today, icon: Clock3, tone: 'text-violet-600 bg-violet-50' }, { label: 'En vivo', metric: data.kpis.live, icon: Radio, tone: 'text-red-600 bg-red-50' }, { label: 'Por jugar', metric: data.kpis.pending, icon: CalendarClock, tone: 'text-amber-600 bg-amber-50' }, { label: 'Docs. pendientes', metric: data.kpis.pendingDocuments, icon: FileCheck2, tone: 'text-orange-600 bg-orange-50' }, { label: 'Sanciones activas', metric: data.kpis.activeSanctions, icon: ShieldAlert, tone: 'text-rose-600 bg-rose-50' },
  ];
  return <div data-testid="operations-dashboard" className="min-w-0 space-y-6 overflow-x-hidden sm:space-y-8">
    <section aria-label="Estado de publicación" className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Publicación del torneo</p><p className="mt-1 text-sm font-black uppercase text-slate-900">{data.publication.state === 'PUBLIC' ? 'Publicado' : data.publication.state === 'DELEGATES_ONLY' ? 'Revisión de delegados' : 'Privado'}</p></div><div className="flex flex-wrap gap-2 text-[9px] font-black uppercase tracking-widest"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-2 ${data.publication.delegates ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{data.publication.delegates ? <Eye size={13} /> : <EyeOff size={13} />} Delegados: {data.publication.delegates ? 'Sí' : 'No'}</span><span className={`inline-flex items-center gap-1 rounded-full px-3 py-2 ${data.publication.public ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>{data.publication.public ? <Eye size={13} /> : <EyeOff size={13} />} Público: {data.publication.public ? 'Sí' : 'No'}</span></div></section>
    <section aria-labelledby="kpi-title"><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-600">Pulso operativo</p><h2 id="kpi-title" className="text-xl font-black uppercase tracking-tight text-slate-950 sm:text-2xl">Estado del torneo</h2></div><span className="hidden text-[10px] font-bold uppercase tracking-widest text-slate-400 sm:block">Datos del torneo seleccionado</span></div><div data-testid="kpi-grid" className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{metrics.map(({ label, metric, icon: Icon, tone }) => <article key={label} aria-label={label} className={`min-w-0 rounded-2xl border bg-white p-4 shadow-sm ${metric.error ? 'border-red-200' : 'border-slate-200'}`}><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone}`}><Icon size={18} aria-hidden="true" /></div><MetricValue metric={metric} label={label} /><p className="mt-2 break-words text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</p></article>)}</div></section>

    <div className="grid gap-5 xl:grid-cols-[1.08fr_.92fr]">
      <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm" aria-labelledby="attention-title"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:p-6"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-600">Control operativo</p><h2 id="attention-title" className="text-xl font-black uppercase tracking-tight text-slate-950">Necesitan atención</h2></div><CircleAlert className="text-amber-500" aria-hidden="true" /></div><div className="divide-y divide-slate-100">{data.alerts.map((alert) => <div key={alert.id} className="p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className={`flex min-w-0 flex-1 items-start gap-3 rounded-2xl border p-4 ${priorityClasses[alert.priority]}`}><span className="flex h-8 min-w-8 items-center justify-center rounded-lg bg-white/70 text-sm font-black">{alert.count ?? (alert.priority === 'success' ? <Check size={17} /> : '!')}</span><div className="min-w-0"><p className="text-xs font-black uppercase tracking-wide">{alert.title}</p><p className="mt-1 text-xs font-semibold leading-relaxed opacity-80">{alert.description}</p></div></div><button type="button" onClick={() => navigate(alert.href)} className="flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-[9px] font-black uppercase tracking-widest text-slate-700 shadow-sm transition hover:border-blue-300 hover:text-blue-700 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-200">{alert.actionLabel}<ArrowRight size={14} aria-hidden="true" /></button></div></div>)}</div></section>

      <section className="rounded-3xl bg-slate-950 p-5 text-white shadow-xl sm:p-6" aria-labelledby="health-title"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-400">Tournament Health Check</p><h2 id="health-title" className="text-xl font-black uppercase tracking-tight">Preparación del torneo</h2><p className="mt-2 max-w-md text-xs font-semibold leading-relaxed text-slate-400">Calculado con criterios verificables y ponderados del torneo activo.</p></div><div className="relative flex h-20 w-20 shrink-0 items-center justify-center rounded-full" style={{ background: `conic-gradient(#2563eb ${data.readiness * 3.6}deg, #1e293b 0deg)` }} aria-label={`${data.readiness}% de preparación`}><div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-950 text-lg font-black">{data.readiness}%</div></div></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{data.checks.map((check) => <button key={check.id} type="button" onClick={() => navigate(check.href)} title={check.detail} className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2.5 text-left transition hover:bg-white/[.08] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${check.status === 'complete' ? 'bg-emerald-500/20 text-emerald-400' : check.status === 'warning' ? 'bg-amber-500/20 text-amber-300' : 'bg-red-500/20 text-red-300'}`}>{check.status === 'complete' ? <Check size={14} /> : <span className="text-xs font-black">!</span>}</span><span className="min-w-0"><span className="block text-[10px] font-black uppercase tracking-wide">{check.label}</span><span className="block text-[9px] font-semibold text-slate-400">{check.detail}</span></span></button>)}</div></section>
    </div>

    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm" aria-labelledby="today-title"><div className="flex items-center justify-between gap-4 border-b border-slate-100 p-5 sm:p-6"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-violet-600">Agenda operativa</p><h2 id="today-title" className="text-xl font-black uppercase tracking-tight text-slate-950">Hoy</h2></div><Gauge className="text-violet-500" aria-hidden="true" /></div>{data.agendaError ? <div role="alert" className="flex items-center gap-3 px-5 py-8 text-red-700"><AlertCircle size={20} /><div><p className="text-sm font-black uppercase">Agenda no disponible</p><p className="text-xs font-semibold">{data.agendaError}</p></div></div> : data.todayMatches.length ? <div className="divide-y divide-slate-100">{data.todayMatches.map((match) => <div key={match.id} className="grid min-w-0 gap-4 p-4 sm:grid-cols-[120px_minmax(0,1fr)_auto] sm:items-center sm:p-5"><div><span className={`inline-flex rounded-full px-3 py-1 text-[8px] font-black uppercase tracking-wider ${match.status === 'LIVE' ? 'bg-red-50 text-red-600' : match.status === 'FINISHED' ? 'bg-slate-100 text-slate-600' : 'bg-blue-50 text-blue-600'}`}>{match.status === 'LIVE' ? 'En vivo' : match.status === 'FINISHED' ? 'Finalizado' : 'Programado'}</span><p className="mt-2 text-[10px] font-black uppercase text-slate-500">{match.scheduledTime?.slice(0, 5) || 'Sin hora'} · {match.venue || 'Sin cancha'}</p></div><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2 text-center sm:gap-3"><p className="truncate text-xs font-black uppercase text-slate-900">{match.homeTeam}</p><span className="rounded-lg bg-slate-950 px-2.5 py-1.5 text-[9px] font-black text-white">{match.status === 'FINISHED' || match.status === 'LIVE' ? `${match.homeScore ?? 0}–${match.awayScore ?? 0}` : 'VS'}</span><p className="truncate text-xs font-black uppercase text-slate-900">{match.awayTeam}</p></div><button type="button" onClick={() => navigate(match.href)} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-[9px] font-black uppercase tracking-widest text-white transition hover:bg-blue-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-200">{match.status === 'FINISHED' ? 'Ver partido' : 'Abrir Mesa'}<ArrowRight size={14} aria-hidden="true" /></button></div>)}</div> : <div data-testid="today-empty-state" className="px-5 py-10 text-center"><CalendarClock className="mx-auto text-slate-300" size={28} aria-hidden="true" /><p className="mt-3 text-sm font-black uppercase text-slate-700">Sin partidos programados para hoy</p><p className="mt-1 text-xs font-semibold text-slate-400">La agenda se alimenta de las fechas reales del fixture.</p></div>}</section>
  </div>;
}
