'use client';
import { useState,type ReactNode } from 'react';
import { ChevronDown,FileText,ShieldAlert,Trophy } from 'lucide-react';
import { formatCopAmount } from '@/app/lib/formatters';
import type { BulletinSnapshot } from '@/app/lib/tournaments/bulletin';

const tones={blue:'border-blue-200 bg-blue-50/70 text-blue-800',emerald:'border-emerald-200 bg-emerald-50/70 text-emerald-800',indigo:'border-indigo-200 bg-indigo-50/70 text-indigo-800',amber:'border-amber-200 bg-amber-50/70 text-amber-800',rose:'border-rose-200 bg-rose-50/70 text-rose-800',violet:'border-violet-200 bg-violet-50/70 text-violet-800'};
type Tone=keyof typeof tones;
function Empty(){return <p className="py-5 text-center text-[9px] font-black uppercase tracking-widest text-slate-400">Sin registros para este boletín</p>}
function Block({title,tone,children}:{title:string;tone:Tone;children:ReactNode}){return <section className={`min-w-0 overflow-hidden rounded-2xl border p-3 sm:p-4 ${tones[tone]}`}><h4 className="mb-2 flex items-center gap-2 text-[9px] font-black uppercase tracking-wider sm:text-[10px] sm:tracking-widest"><Trophy className="shrink-0" size={14}/>{title}</h4><div className="min-w-0 text-slate-800">{children}</div>{title==='Posiciones'&&<p className="mt-3 border-t border-indigo-200 pt-2 text-[8px] font-black uppercase leading-relaxed text-indigo-600">Desempate: 1. Juego limpio · 2. Diferencia de gol · 3. Goles a favor</p>}</section>}

export default function TournamentBulletinCard({snapshot,number,confirmedAt,preview=false,onConfirm,busy=false,initialOpen=false}:{snapshot:BulletinSnapshot;number:number;confirmedAt?:string;preview?:boolean;onConfirm?:()=>void;busy?:boolean;initialOpen?:boolean}){
 const[open,setOpen]=useState(initialOpen);
 return <section className="overflow-hidden rounded-3xl border border-indigo-200 bg-white shadow-sm">
  <button type="button" onClick={()=>setOpen(!open)} className="flex w-full items-center gap-4 bg-gradient-to-r from-slate-950 via-indigo-950 to-blue-950 p-5 text-left text-white"><span className="rounded-2xl bg-indigo-400/20 p-3 text-indigo-200"><FileText/></span><span className="flex-1"><span className="block text-[9px] font-black uppercase tracking-[.22em] text-indigo-300">{preview?'Vista previa sin publicar':'Documento oficial inmutable'}</span><b className="block text-lg uppercase">Boletín No. {number}</b><small className="font-semibold text-slate-300">Resultados, posiciones, goleadores, disciplina y deudas</small></span><ChevronDown className={`transition ${open?'rotate-180':''}`}/></button>
  {open&&<div className="space-y-7 bg-gradient-to-b from-indigo-50/40 to-white p-5">{snapshot.categories.map(c=>{
   const fairPlay=[...c.standings].sort((a,b)=>Number(b.points??0)-Number(a.points??0)||Number(b.fair_play_points??0)-Number(a.fair_play_points??0)||(Number(b.goals_for??0)-Number(b.goals_against??0))-(Number(a.goals_for??0)-Number(a.goals_against??0))||Number(b.goals_for??0)-Number(a.goals_for??0)||String(a.name).localeCompare(String(b.name),'es'));
   return <article key={c.id} className="min-w-0"><h3 className="mb-3 break-words text-base font-black uppercase text-slate-900 sm:text-lg">{c.sport} · {c.name} · Fecha {c.round||'—'}</h3><div className="grid min-w-0 gap-3 lg:grid-cols-2">
    <Block title="Resultados" tone="blue">{c.results.length?c.results.map(m=><p key={m.id} className="grid min-w-0 grid-cols-[minmax(0,1fr)_54px_minmax(0,1fr)] items-center gap-2 border-b border-blue-100 py-3 text-[10px] sm:grid-cols-[minmax(0,1fr)_72px_minmax(0,1fr)] sm:gap-3 sm:text-xs"><b className="min-w-0 break-words leading-tight">{m.home}</b><b className="rounded-lg bg-blue-600 px-1 py-1.5 text-center text-white">{m.homeScore} - {m.awayScore}</b><b className="min-w-0 break-words text-right leading-tight">{m.away}</b></p>):<Empty/>}</Block>
    <Block title="Goleadores" tone="emerald">{c.scorers.length?c.scorers.map((p,i)=><p key={p.id} className="flex justify-between border-b border-emerald-100 py-2 text-xs"><span><b>{i+1}. {p.name}</b> · {p.team}</span><b>{p.total}</b></p>):<Empty/>}</Block>
    <Block title="Posiciones" tone="indigo"><div className="overflow-x-auto"><table className="w-full min-w-[430px] text-[9px]"><thead><tr><th className="text-left">Equipo</th>{['PJ','PG','PE','PP','GF','GC','DG','PTS'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{c.standings.map((t,i)=><tr key={t.id} className="border-t border-indigo-100 text-center"><td className="py-2 text-left font-black">{i+1}. {t.name}</td><td>{t.played}</td><td>{t.won}</td><td>{t.drawn}</td><td>{t.lost}</td><td>{t.goals_for}</td><td>{t.goals_against}</td><td>{t.goals_for-t.goals_against}</td><td className="font-black text-indigo-700">{t.points}</td></tr>)}</tbody></table></div></Block>
    <Block title="Amonestados y expulsados" tone="amber">{c.cards.length?c.cards.map(x=><p key={x.id} className="flex justify-between border-b border-amber-100 py-2 text-xs"><span>{x.player} · {x.team}</span><b className={String(x.card).startsWith('Roja')?'text-red-600':'text-amber-600'}>{x.card}</b></p>):<Empty/>}</Block>
    <Block title="Deudas" tone="rose">{c.debts.length?c.debts.map(x=><p key={x.team} className="flex justify-between border-b border-rose-100 py-2 text-xs"><b>{x.team}</b><b className="text-red-600">{formatCopAmount(x.amount)}</b></p>):<Empty/>}</Block>
    <Block title="Comité disciplinario" tone="violet">{c.sanctions.length?c.sanctions.map(x=><div key={x.id} className="border-b border-violet-100 py-2 text-xs"><b>{x.player} · {x.team} · {x.matches} fecha(s)</b><p className="text-slate-500">{x.comment}</p></div>):<Empty/>}</Block>
    {c.fairPlayEnabled!==false&&<Block title="Clasificación · desempate por Juego Limpio" tone="emerald"><div className="grid grid-cols-[36px_minmax(0,1fr)_58px_72px] gap-2 border-b border-emerald-200 pb-2 text-[8px] font-black uppercase tracking-wider text-emerald-700"><span>Pos.</span><span>Equipo</span><span className="text-center">PTS</span><span className="text-center">JL</span></div><div>{fairPlay.map((team,index)=><div key={team.id} className="grid grid-cols-[36px_minmax(0,1fr)_58px_72px] items-center gap-2 border-b border-emerald-100 py-2.5 text-[10px]"><b className="text-emerald-700">{index+1}.</b><span className="truncate font-black">{team.name}</span><b className="rounded-md bg-slate-900 px-2 py-1 text-center text-white">{team.points??0}</b><b className="rounded-md bg-emerald-100 px-2 py-1 text-center text-emerald-700">{team.fair_play_points??0}</b></div>)}</div><p className="mt-2 text-[8px] font-bold uppercase text-emerald-600">Orden: 1. Puntos del torneo · 2. Juego Limpio · 3. Diferencia de gol · 4. Goles a favor</p></Block>}
   </div></article>})}{!snapshot.categories.length&&<Empty/>}{preview&&onConfirm&&<button disabled={busy} onClick={onConfirm} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-blue-600 p-4 text-xs font-black uppercase tracking-widest text-white shadow-lg disabled:opacity-50"><ShieldAlert size={16}/> Confirmar y bloquear boletín</button>}{!preview&&<p className="text-[9px] font-black uppercase tracking-widest text-emerald-600">Confirmado {confirmedAt?new Date(confirmedAt).toLocaleString('es-CO'):''} · No admite modificaciones</p>}</div>}
 </section>;
}
