'use server';
import { hasAdminSession } from '@/app/lib/auth';
import { createServerSupabaseAdminClient } from '@/app/lib/supabase/server';
import { getClientIdBySlug } from '@/app/lib/tenant';
import { buildBulletinSnapshot, hydrateDynamicBulletinFields, stampSuspensionOrigins } from '@/app/lib/tournaments/bulletin';
import { revalidatePath } from 'next/cache';

async function owned(slug:string,tournamentId:string){if(!(await hasAdminSession(slug)))return null;const clientId=await getClientIdBySlug(slug);const db=createServerSupabaseAdminClient();const {data}=await db.from('tournaments').select('id').eq('id',tournamentId).eq('client_id',clientId||'').maybeSingle();return data?db:null}
export async function loadBulletinEditor(slug:string,tournamentId:string){const db=await owned(slug,tournamentId);if(!db)return null;const [{data:published},snapshot]=await Promise.all([db.from('tournament_bulletins').select('id,bulletin_number,confirmed_at,snapshot').eq('tournament_id',tournamentId).order('bulletin_number',{ascending:false}),buildBulletinSnapshot(db,tournamentId)]);const bulletins=published||[],currentNumber=Number(bulletins[0]?.bulletin_number||0);return{published:bulletins.map((item:any)=>({...item,snapshot:hydrateDynamicBulletinFields(item.snapshot,snapshot,currentNumber)})),preview:snapshot,nextNumber:currentNumber+1}}
export async function confirmBulletin(slug:string,tournamentId:string,expectedNumber:number){const db=await owned(slug,tournamentId);if(!db)return{success:false as const,error:'Sesión no válida.'};const {data:latest}=await db.from('tournament_bulletins').select('bulletin_number,snapshot').eq('tournament_id',tournamentId).order('bulletin_number',{ascending:false}).limit(1).maybeSingle();const next=Number(latest?.bulletin_number||0)+1;if(expectedNumber!==next)return{success:false as const,error:'Ya se publicó otro boletín. Actualiza la página.'};let snapshot=await buildBulletinSnapshot(db,tournamentId);snapshot=stampSuspensionOrigins(snapshot,next,latest?.snapshot);if(!snapshot.categories.length)return{success:false as const,error:'El torneo no tiene categorías para publicar.'};const {error}=await db.from('tournament_bulletins').insert({tournament_id:tournamentId,bulletin_number:next,snapshot});if(error)return{success:false as const,error:'No se pudo confirmar el boletín.'};revalidatePath(`/${slug}/admin`);revalidatePath(`/${slug}/delegado`);return{success:true as const}}
