'use server';
import { hasAdminSession } from '@/app/lib/auth';
import { createServerSupabaseAdminClient } from '@/app/lib/supabase/server';
import { getClientIdBySlug } from '@/app/lib/tenant';
import { buildBulletinSnapshot, hydrateDynamicBulletinFields, stampSuspensionOrigins } from '@/app/lib/tournaments/bulletin';
import { revalidatePath } from 'next/cache';
import { nextDate } from '@/app/lib/date-filter';

async function owned(slug:string,tournamentId:string){if(!(await hasAdminSession(slug)))return null;const clientId=await getClientIdBySlug(slug);const db=createServerSupabaseAdminClient();const {data}=await db.from('tournaments').select('id').eq('id',tournamentId).eq('client_id',clientId||'').maybeSingle();return data?db:null}
export async function loadBulletinEditor(slug:string,tournamentId:string,requestedNumber?:number,asOfDate?:string|null){const db=await owned(slug,tournamentId);if(!db)return null;let bulletinsQuery=db.from('tournament_bulletins').select('id,bulletin_number,confirmed_at,snapshot').eq('tournament_id',tournamentId).order('bulletin_number',{ascending:false});if(asOfDate)bulletinsQuery=bulletinsQuery.lt('confirmed_at',`${nextDate(asOfDate)}T00:00:00-05:00`);const [{data:published},snapshot]=await Promise.all([bulletinsQuery,buildBulletinSnapshot(db,tournamentId,asOfDate)]);const bulletins=published||[],currentNumber=Number(bulletins[0]?.bulletin_number||0),nextNumber=currentNumber+1,previewNumber=Number.isSafeInteger(requestedNumber)&&Number(requestedNumber)>=nextNumber?Number(requestedNumber):nextNumber;return{published:bulletins.map((item:any)=>({...item,snapshot:hydrateDynamicBulletinFields(item.snapshot,snapshot,currentNumber)})),preview:hydrateDynamicBulletinFields(stampSuspensionOrigins(snapshot,previewNumber,bulletins[0]?.snapshot),snapshot,previewNumber),nextNumber,previewNumber}}
export async function confirmBulletin(slug:string,tournamentId:string,requestedNumber:number){const db=await owned(slug,tournamentId);if(!db)return{success:false as const,error:'Sesión no válida.'};const {data:latest}=await db.from('tournament_bulletins').select('bulletin_number,snapshot').eq('tournament_id',tournamentId).order('bulletin_number',{ascending:false}).limit(1).maybeSingle();const minimumNext=Number(latest?.bulletin_number||0)+1;if(!Number.isSafeInteger(requestedNumber)||requestedNumber<1)return{success:false as const,error:'El número del boletín debe ser un entero positivo.'};if(requestedNumber<minimumNext)return{success:false as const,error:`El número debe ser como mínimo el No. ${minimumNext}. Actualiza la página si es necesario.`};let snapshot=await buildBulletinSnapshot(db,tournamentId);snapshot=stampSuspensionOrigins(snapshot,requestedNumber,latest?.snapshot);if(!snapshot.categories.length)return{success:false as const,error:'El torneo no tiene categorías para publicar.'};const {error}=await db.from('tournament_bulletins').insert({tournament_id:tournamentId,bulletin_number:requestedNumber,snapshot});if(error)return{success:false as const,error:error.code==='23505'?'Ese número de boletín ya fue utilizado. Actualiza la página.':'No se pudo confirmar el boletín.'};revalidatePath(`/${slug}/admin`);revalidatePath(`/${slug}/delegado`);return{success:true as const}}
