'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ClipboardList, History, Plus, X } from 'lucide-react';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { supabase } from '../../../supabase';
import { loadParticipationData, saveManualParticipation, voidParticipation } from './actions';
import { REQUIRED_REGULAR_PARTICIPATIONS } from '@/app/lib/competition/participation';

export default function ParticipationAdmin({ slug, initialCategoryId }: { slug: string; initialCategoryId: string }) {
  const [categories, setCategories] = useState<any[]>([]); const [categoryId, setCategoryId] = useState(initialCategoryId); const [data, setData] = useState<any>(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ teamId: '', playerId: '', matchId: '', comment: '' });
  const [search, setSearch] = useState(''); const [filterTeamId, setFilterTeamId] = useState(''); const [filterDate, setFilterDate] = useState('');
  const [selectedPlayerId, setSelectedPlayerId] = useState<string | null>(null);
  useEffect(() => { supabase.from('categories').select('id,name,tournaments!inner(client_id)').order('name').then(({ data }: { data: any[] | null }) => { setCategories(data || []); if (!categoryId && data?.[0]) setCategoryId(data[0].id); }); }, []);
  const reload = async () => { if (!categoryId) return; setBusy(true); const result = await loadParticipationData(slug, categoryId); if (!result.success) toast.error(result.error); else setData(result.data); setBusy(false); };
  useEffect(() => { reload(); }, [categoryId]);
  const counts = useMemo(() => { const map = new Map<string, Set<string>>(); for (const record of [...(data?.records || []), ...(data?.eventRecords || [])]) if (record.status !== 'VOIDED') { const set = map.get(record.player_id) || new Set(); set.add(record.match_id); map.set(record.player_id, set); } return map; }, [data]);
  const team = data?.teams?.find((item: any) => item.id === form.teamId);
  const selectedTeamPlayers = team?.players || [];
  const regularMatches = (data?.matches || []).filter((match: any) => match.matchdays?.competition_stages?.stage_type !== 'FINALS' && (!form.teamId || match.home_team_id === form.teamId || match.away_team_id === form.teamId));
  const matchById = new Map<string, any>((data?.matches || []).map((match: any) => [match.id, match]));
  const playerById = new Map<string, any>((data?.teams || []).flatMap((item: any) => (item.players || []).map((player: any) => ({ ...player, team_id: item.id, teamName: item.name }))).map((player: any) => [player.id, player]));
  const visiblePlayers = (data?.teams || []).flatMap((item: any) => (item.players || []).map((player: any) => ({ ...player, team_id: item.id, teamName: item.name, count: counts.get(player.id)?.size || 0 }))).filter((player: any) => (!filterTeamId || player.team_id === filterTeamId) && (!filterDate || [...(data?.records || []), ...(data?.eventRecords || [])].some((record: any) => record.player_id === player.id && matchById.get(record.match_id)?.matchdays?.scheduled_date === filterDate)) && (!search || `${player.name} ${player.teamName}`.toLowerCase().includes(search.toLowerCase())));
  const participationRows = [...(data?.records || []), ...(data?.eventRecords || [])].filter((record: any) => record.status !== 'VOIDED' && (!filterTeamId || record.team_id === filterTeamId) && (!filterDate || matchById.get(record.match_id)?.matchdays?.scheduled_date === filterDate) && (!search || `${playerById.get(record.player_id)?.name || ''} ${playerById.get(record.player_id)?.teamName || ''}`.toLowerCase().includes(search.toLowerCase()))).sort((a:any,b:any) => String(matchById.get(a.match_id)?.matchdays?.scheduled_date || '').localeCompare(String(matchById.get(b.match_id)?.matchdays?.scheduled_date || '')));
  const selectedPlayer = selectedPlayerId ? playerById.get(selectedPlayerId) : null;
  const selectedPlayerEvents = [
    ...(data?.playerEvents || []).filter((event: any) => event.player_id === selectedPlayerId),
    ...(data?.records || []).filter((record: any) => record.player_id === selectedPlayerId && record.status === 'CONFIRMED').map((record: any) => ({ ...record, event_type: 'PARTICIPATION_MANUAL', matches: matchById.get(record.match_id) })),
  ].sort((a: any, b: any) => String(a.matches?.matchdays?.scheduled_date || a.created_at || '').localeCompare(String(b.matches?.matchdays?.scheduled_date || b.created_at || '')));
  const eventLabel = (type: string) => ({ GOAL: 'Gol', BASKET_1: 'Canasta 1 punto', BASKET_2: 'Canasta 2 puntos', BASKET_3: 'Canasta 3 puntos', YELLOW: 'Tarjeta amarilla', RED: 'Tarjeta roja', STARTING_LINEUP: 'Titular', SUB_IN: 'Ingresó', SUB_OUT: 'Salió', FOUL: 'Falta', MVP: 'MVP', PARTICIPATION_MANUAL: 'Participación manual' } as Record<string, string>)[type] || type;
  async function add() { if (!form.teamId || !form.playerId || !form.matchId) return toast.error('Selecciona equipo, jugador y partido.'); setBusy(true); const result = await saveManualParticipation(slug, { categoryId, ...form }); if (!result.success) toast.error(result.error); else { toast.success('Participación registrada.'); setForm(current => ({ ...current, playerId: '', matchId: '', comment: '' })); await reload(); } setBusy(false); }
  async function remove(id: string) { const comment = window.prompt('Motivo de la anulación') || ''; if (!comment.trim()) return; setBusy(true); const result = await voidParticipation(slug, id, comment); if (!result.success) toast.error(result.error); else { toast.success('Participación anulada.'); await reload(); } setBusy(false); }
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-6xl"><Link href={`/${slug}/admin`} className="mb-6 inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-[10px] font-black uppercase tracking-wider text-slate-600 shadow-sm"><ArrowLeft size={15} /> Panel principal</Link><header className="mb-7 flex items-center gap-3"><span className="rounded-2xl bg-blue-600 p-3 text-white shadow-lg shadow-blue-600/20"><ClipboardList size={25} /></span><div><h1 className="text-2xl font-black uppercase tracking-tight text-slate-950 md:text-3xl">Participación fase regular</h1><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Mínimo {REQUIRED_REGULAR_PARTICIPATIONS} partidos para fase final</p></div></header>
    <label className="mb-6 block text-[10px] font-black uppercase tracking-widest text-slate-500">Categoría<select value={categoryId} onChange={event => setCategoryId(event.target.value)} className="mt-2 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-sm font-black shadow-sm">{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
    <section className="mb-6 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><h2 className="mb-4 text-base font-black uppercase tracking-tight text-slate-900">Registrar participación manual</h2><div className="grid gap-3 md:grid-cols-4"><select value={form.teamId} onChange={event => setForm({ ...form, teamId: event.target.value, playerId: '', matchId: '' })} className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-black"><option value="">Primero selecciona el equipo</option>{(data?.teams || []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={form.playerId} disabled={!form.teamId} onChange={event => setForm({ ...form, playerId: event.target.value })} className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-black disabled:opacity-50"><option value="">{form.teamId ? 'Selecciona el jugador' : 'Selecciona un equipo primero'}</option>{selectedTeamPlayers.map((item: any) => <option key={item.id} value={item.id}>#{item.shirt_number || '-'} {item.name}</option>)}</select><select value={form.matchId} disabled={!form.teamId} onChange={event => setForm({ ...form, matchId: event.target.value })} className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-black disabled:opacity-50"><option value="">{form.teamId ? 'Partido regular' : 'Selecciona un equipo primero'}</option>{regularMatches.map((match: any) => <option key={match.id} value={match.id}>J{match.matchdays?.round_number || '-'} · {data.teams.find((item: any) => item.id === match.home_team_id)?.name} vs {data.teams.find((item: any) => item.id === match.away_team_id)?.name}</option>)}</select><input value={form.comment} onChange={event => setForm({ ...form, comment: event.target.value })} placeholder="Motivo / soporte" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /><button type="button" disabled={busy} onClick={add} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 p-3 text-[10px] font-black uppercase tracking-widest text-white shadow-lg shadow-blue-600/20 disabled:opacity-50 md:col-span-4"><Plus size={16} /> Registrar participación</button></div></section>
    <section className="overflow-hidden rounded-3xl border bg-white"><div className="border-b p-5"><h2 className="text-lg font-black uppercase">Estado de jugadores</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar jugador o equipo" className="rounded-xl border p-3 text-sm" /><select value={filterTeamId} onChange={event => setFilterTeamId(event.target.value)} className="rounded-xl border p-3 text-sm font-bold"><option value="">Todos los equipos</option>{(data?.teams || []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="date" value={filterDate} onChange={event => setFilterDate(event.target.value)} className="rounded-xl border p-3 text-sm" /></div></div><div className="divide-y">{visiblePlayers.map((player: any) => <button type="button" key={player.id} onClick={() => setSelectedPlayerId(player.id)} className="flex w-full flex-wrap items-center justify-between gap-3 p-4 text-left transition hover:bg-blue-50"><div><p className="font-black uppercase">{player.name}</p><p className="text-xs font-bold uppercase text-slate-500">{player.teamName} · {player.count}/{REQUIRED_REGULAR_PARTICIPATIONS} partidos</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-blue-600"><History size={12} className="mr-1 inline" /> Ver historial completo</p></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${player.count >= REQUIRED_REGULAR_PARTICIPATIONS ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{player.count >= REQUIRED_REGULAR_PARTICIPATIONS ? 'Habilitado' : 'Pendiente'}</span></button>)}{visiblePlayers.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No hay jugadores con esos filtros.</p>}</div></section>
    <section className="mt-6 rounded-3xl border bg-white p-5"><h2 className="mb-3 text-lg font-black uppercase">Participaciones por fecha</h2>{participationRows.map((record: any) => { const match = matchById.get(record.match_id); const player = playerById.get(record.player_id); return <div key={`${record.id || record.event_type}-${record.match_id}-${record.player_id}`} className="flex flex-wrap items-center justify-between gap-3 border-b py-3 text-xs"><span><b>{player?.name || 'Jugador'}</b> · {player?.teamName || 'Equipo'} · {match?.matchdays?.scheduled_date || 'Fecha pendiente'} · Jornada {match?.matchdays?.round_number || '-'} · {record.source === 'MANUAL' ? 'Manual' : 'Evento'}</span>{record.source === 'MANUAL' && record.status === 'CONFIRMED' && <button type="button" onClick={() => remove(record.id)} className="rounded-lg p-2 text-red-600" aria-label="Anular participación"><X size={15} /></button>}</div>; })}{participationRows.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No hay participaciones con esos filtros.</p>}</section>
    {selectedPlayer && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="presentation" onClick={() => setSelectedPlayerId(null)}><section role="dialog" aria-modal="true" aria-labelledby="player-history-title" onClick={event => event.stopPropagation()} className="max-h-[88dvh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-5 shadow-2xl md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Resumen del torneo</p><h2 id="player-history-title" className="mt-1 text-2xl font-black uppercase">{selectedPlayer.name}</h2><p className="text-xs font-bold uppercase text-slate-500">{selectedPlayer.teamName} · {counts.get(selectedPlayer.id)?.size || 0}/{REQUIRED_REGULAR_PARTICIPATIONS} partidos de fase regular</p></div><button type="button" onClick={() => setSelectedPlayerId(null)} aria-label="Cerrar historial" className="rounded-xl p-2 hover:bg-slate-100"><X /></button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{['GOAL', 'YELLOW', 'RED', 'STARTING_LINEUP'].map(type => <div key={type} className="rounded-2xl bg-slate-50 p-3"><p className="text-xl font-black">{selectedPlayerEvents.filter((event: any) => event.event_type === type).length}</p><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">{eventLabel(type)}</p></div>)}</div><h3 className="mt-6 border-b pb-2 text-sm font-black uppercase">Eventos registrados</h3><div className="divide-y">{selectedPlayerEvents.map((event: any) => <div key={event.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-black uppercase">{eventLabel(event.event_type)}</p><p className="text-[10px] font-bold uppercase text-slate-500">{event.matches?.matchdays?.scheduled_date || 'Fecha pendiente'} · Jornada {event.matches?.matchdays?.round_number || '-'} · {event.matches?.home_team?.name || 'Local'} vs {event.matches?.away_team?.name || 'Visitante'}</p>{event.minute_record != null && <p className="text-[10px] text-slate-400">Minuto {event.minute_record}'</p>}</div><span className="text-[10px] font-black uppercase text-slate-500">{event.source === 'MANUAL' ? 'Manual' : event.fine_status === 'PAID' ? 'Pagado' : ''}</span></div>)}{selectedPlayerEvents.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No hay eventos registrados para este jugador.</p>}</div></section></div>}
  </div></main>;
}
